#!/usr/bin/env python3

tiles = {'A': 9, 'B': 2, 'C': 2, 'D': 4, 'E': 12, 'F': 2, 
        'G': 3, 'H': 2, 'I': 9, 'J': 1, 'K': 1, 'L': 4, 
        'M': 2, 'N': 6, 'O': 8, 'P': 2, 'Q': 1, 'R': 6, 
        'S': 4, 'T': 6, 'U': 4, 'V': 2, 'W': 2, 'X': 1, 
        'Y': 2, 'Z': 1, '_': 2}

def main():
    invalid = False
    tilesInPlay = input("gimme tiles: ").upper()
    for letter in tilesInPlay:
        if tiles[letter] > 0:
            tiles[letter] = tiles[letter]-1
        else:
            invalid = True
            print("Invalid Input: More "+letter+"'s have been "
                    "taken from the bag than possible")
    if not invalid:
        for i in range(12,0,-1):
            filtered = list(filter(lambda t: t[1]==i, tiles.items()))
            if filtered:
                letters = (", ").join(sorted([l[0] for l in filtered]))
                print(str(i)+":",letters)

if __name__ == "__main__":
    main()
