#!/usr/bin/env python

class Key:
    def __init__(self,rawLines):
        self.keyDict = {}
        self._createDict(rawLines)

    def _createDict(self,rawLines):
        for y in range(len(rawLines)):
            line = rawLines[y]
            for x in range(len(line)):
                char = line[x]
                if char != ' ':
                    self.keyDict[char] = (x,y)
                    print(line[x],x,y)

def readKeyFile():
    f = open('mirrorKey.txt', 'r')
    linesList = f.readlines()
    f.close()
    return [l.replace("\n","") for l in linesList]

def keyMatrix(keyList):
    array = []
    for line in keyList:
        array.append(list(line))
    return array

def main():
    key = Key(readKeyFile())

if __name__ == "__main__":
    main()
