#!/usr/bin/env python

class Key:
    def __init__(self,lineArr):
        self.keyDict = {}
        self._createDict(lineArr)

    def _createDict(self,lineArr):
        for y in range(len(lineArr)):
            line = lineArr[y]
            for x in range(len(line)):
                char = line[x]
                if char != ' ':
                    self.keyDict[char] = (x,y)
                    #print(line[x],x,y)

class Puzzle:
    def __init__(self,lineArr):
        self.puzzleDict = {}
        self._createDict(lineArr)

    def _createDict(self,lineArr):
        for y in range(len(lineArr)):
            line = lineArr[y]
            for x in range(len(line)):
                char = line[x]
                self.puzzleDict[(x,y)]=char
        print(self.puzzleDict)

def readFile(filename):
    f = open(filename, 'r')
    linesList = f.readlines()
    f.close()
    return [l.replace("\n","") for l in linesList]

def main():
    key = Key(readFile("mirrorKey.txt"))
    
    totalPuzz = readFile("mirrorTest.txt")
    encryptedStr, puzzleGrid = totalPuzz[-1], totalPuzz[0:len(totalPuzz)-1]
    
    puzzle = Puzzle(puzzleGrid)

if __name__ == "__main__":
    main()
