#!/usr/bin/env python3

def main():
    num = int(input("Please enter a number: "))
    
    while(num != 1):
        if num%3 == 0:
            print(str(num)," 0")
            num = num//3
        elif num%3 == 1:
            print(str(num),"-1")
            num = (num-1)//3
        else:
            print(str(num),"+1")
            num = (num+1)//3
    
    print(num,"...hooray!")

if __name__ == "__main__":
    main()
