#!/usr/bin/env python3
import sys
from random import shuffle
from copy import copy

# Person Class
class Person():

    def __init__(self, name):
        self.name = name
        self.famMembers = []
        self.getsGiftFrom = None

    def getName(self):
        return self.name

    def addFam(self, personList):
        self.famMembers = personList
        if self.name in self.famMembers:
            self.famMembers.remove(self.name)

    def setSanta(self, person):
        self.getsGiftFrom = person

    def hasSanta(self):
        if self.getsGiftFrom:
            return True
        return False

    def isRelatedTo(self, person):
        return person.getName() in self.famMembers

    def __str__(self):
        return self.name

def readFile(fName):
    with open(fName) as f:
        content = f.read()
    content = content.split("\n")
    return content

def createPeople(peopleString):
    peopleList = []
    familyPeople = []

    for line in peopleString:
        family = line.split(" ")
        for name in family:
            newPerson = Person(name)
            if len(family) > 1:
                newPerson.addFam(copy(family))
                familyPeople.append(newPerson)
            peopleList.append(newPerson)
    return peopleList, familyPeople

def assignSantas(people):
    while people:
        shuffle(people)
        p1 = people[0]
        p2 = people[1]

        if p1.isSanta() and p1.hasSanta():
            people.remove(p1)

        while p1 == p2 or p1.isRelatedTo(p2):
            shuffle(people)
            p2 = people[0]

def main():
    content = readFile(sys.argv[1])
    people, familyPeople = createPeople(content)
    assignSantas(people, familyPeople)


if __name__ == "__main__":
    main()
