#!/usr/bin/env python3
import sys
from copy import copy

# Person Class
class Person():

    def __init__(self, name):
        self.name = name
        self.famMembers = []

    def getName(self):
        return self.name

    def addFam(self, personList):
        self.famMembers = personList
        if self.name in self.famMembers:
            self.famMembers.remove(self.name)

    def hasFam(self):
        if not self.famMembers:
            return False
        return True

    def isRelated(self, person):
        return person in self.famMembers

    def __str__(self):
        return self.name

def readFile(fName):
    with open(fName) as f:
        content = f.read()
    content = content.split("\n")
    return content

def createPeople(peopleString):
    peopleList = []
    
    for line in peopleString:
        family = line.split(" ")
        for name in family:
            newPerson = Person(name)
            if len(family) > 1:
                newPerson.addFam(copy(family))
            peopleList.append(newPerson)

    for thing in peopleList:
        print(thing,thing.hasFam())

def main():
    content = readFile(sys.argv[1])
    createPeople(content)

if __name__ == "__main__":
    main()
